thread: Project_thread
	gcc Project_thread.c -o Project_thread

origin: Project
	gcc Project.c -o Project
nice: Project_nice
	gcc Project_nice.c -o Project_nice
	
linux: linux_sched_function
	gcc linux_sched_function.c -o linux_sched_function

test: test_
	gcc test_.c -o test

real_time: thread_real_time
	gcc thread_real_time.c -o thread_real_time